### ISSUE TITLE
ClearText error on Android 10

### ISSUE THREAD

**Issue by kerat71** [mstoer/HomeWeather#1]
Hi, thank you for the app, but I can't used on Android 10. It stops with "net::ERR_CLEARTEXT_NOT_PERMITTED"
I know it's been a while, but can you please update the app?
Greetings,
Milen

**Comment by mstoer** [comment]
I don't have Android 10, only Android 9.  However, there is a change I made for Android 9 that might work for you as well and I update the project.

**Comment by kerat71** [comment]
I am sorry, but I can't find the apk file

**Comment by mstoer** [comment]
OK, try again. I haven't used Android Studio in a while and it required me to run several updates and rebuilds before I could get this updated.  I do not have Android 10, but this does work on Android 9 which had the same error I already fixed last year (but I forgot to update it here).

**Comment by kerat71** [comment]
It's OK now. Thanks 👍

**Comment by kerat71** [comment]
Hi, it would be very useful to add widget to HomeWeather app, have you thought about that?

**Comment by mstoer** [comment]
Hi,  I am not into software that much, so I only do what is needed.  This was put into public domain so anyone can use it or create their own modification of it.   The original issue is resolved, so I am going to close this case.  You can comment on the instructable if you are interested in talking about expanding features.
